using System;
namespace CSharp9._0
{
    public class TopLevelStatements
    {
        public TopLevelStatements()
        {
        }
    }
}

//The above statements are generated by default when you add empty class.
//you can add below code snipped inside toplevelstatements class to make this class executing as main class
/*
public static void Main(string[] args)
{
  Console.WriteLine("Hello World");
}
*/

/*******************************************************************
 * There’s only one line of code that does anything.
 * With top-level statements, you can replace all that boilerplate with the using statement and the single line that does the work:
 * 
 * using System;
 * Console.WriteLine("Hello World!");
 * 
 * If you wanted a one-line program, you could remove the using directive and use the fully qualified type name:
 * 
 * System.Console.WriteLine("Hello World!");
 * 
 * One of the most common uses for this feature is creating teaching materials. 
 * Beginner C# developers can write the canonical “Hello World!” in one or two lines of code. 
 * None of the extra ceremony is needed. However, seasoned developers will find many uses for this feature as well. 
 * Top-level statements enable a script-like experience for experimentation similar to what Jupyter notebooks provide. 
 * Top-level statements are great for small console programs and utilities. Azure functions are an ideal use case for top-level statements.
*******************************************************************/